### ISSUE TITLE
Json parsing error

### ISSUE THREAD

**Issue by Wertik** [ItsLewizzz/DeluxeCoinflipAPI#1]
Came across an error with json parsing. No wrong behaviour reported.

// I don't have the resource bought (I'm only an administrator, don't have the access), so I decided to rather report it here.

```[14:58:04 INFO]: Zenikan issued server command: /cf
[14:58:06 WARN]: [DeluxeCoinflip] Plugin DeluxeCoinflip v1.8.6 generated an exception while executing task 6278825
java.lang.IllegalStateException: Not a JSON Object: null
at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[patched_1.16.3.jar:git-Yatopia-"62a4ea7"]
at fun.lewisdev.coinflip.menu.Base64Util.getUrl(Base64Util.java:58) ~[?:?]
at fun.lewisdev.coinflip.menu.Base64Util.getSkull(Base64Util.java:76) ~[?:?]
at fun.lewisdev.coinflip.game.CoinflipGame.lambda$new$0(CoinflipGame.java:26) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Yatopia-"62a4ea7"]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.3.jar:git-Yatopia-"62a4ea7"]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Yatopia-"62a4ea7"]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by ItsLewizzz** [comment]
This has nothing to do with the API. This has came from the plugin itself. You can get support for verified customers in the support Discord.

**Comment by Wertik** [comment]
> This has nothing to do with the API. This has came from the plugin itself.

Misread the repo name. Sorry. 

> You can get support for verified customers in the support Discord.

I'm not and won't be a verified buyer. Fixing or ignoring this exception is your choice. It doesn't affect the behavior, so it's not needed.
